import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import { db } from '../../lib/firebase';

const defaultCourses = [
  {
    title: 'Sun\'iy intellekt asoslari',
    description: 'Zamonaviy Sun\'iy Intellekt texnologiyalariga kirish, ularning ishlash mexanizmlari va imkoniyatlari.',
    thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=500&q=80',
    modules: [
        { id: 'm1', title: 'Sun\'iy intellekt nima?', content: 'Sun\'iy intellekt (AI - Artificial Intelligence) – bu kompyuter tizimlarining inson kabi fikrlash, qaror qabul qilish, o\'rganish va muammolarni hal qilish qobiliyatidir. Bugungi kunda sun\'iy intellekt hayotimizning har bir sohasiga – tibbiyotdan tortib ta\'limgacha kirib kelgan. AIning asosiy turlari: Zaif AI (Weak AI) – faqat ma\'lum bir vazifani bajarishga mo\'ljallangan (masalan, ovozli yordamchilar yoki shaxmat o\'ynaydigan dasturlar). Kuchli AI (Strong AI) – inson kabi to\'liq aqlga, tahlil qilish va mustaqil fikrlarga ega bo\'lgan hozircha nazariy bosqichdagi tizimlardir. Ushbu modulda sun\'iy intellekt tarixi va Alan Tyuring tajribalari haqida batafsil bilib olasiz.', videoUrl: '' },
        { id: 'm2', title: 'Mashinali o\'rganish (Machine Learning)', content: 'Mashinalarni o\'rganish (Machine Learning) – bu AI tarkibidagi yirik bir yo\'nalish bo\'lib, tizimlarni dasturlashtirmasdan, balki ularga katta ma\'lumotlar (Data) berish orqali mustaqil o\'rganishga o\'rgatish jarayonidir. Unda 3 ta asosiy yondashuv mavjud: 1. Nazorat ostonasida o\'rganish (Supervised Learning) - model oldindan belgilangan to\'g\'ri javoblari bor ma\'lumotlar ustida o\'qiydi. 2. Nazoratsiz o\'rganish (Unsupervised Learning) - model ma\'lumotlar orasidagi o\'xshashliklarni javoblarsiz o\'zi izlaydi. 3. Mukofotlash orqali o\'rganish (Reinforcement Learning) - algoritm qilingan to\'g\'ri harakat uchun mukofotlanadi va shu orqali tajriba orttiradi.', videoUrl: '' },
        { id: 'm3', title: 'Neyron tarmoqlar (Neural Networks)', content: 'Neyron tarmoqlar (Neural Networks) inson miyasining tuzilishidan ilhomlangan holda yaratilgan matematik modellar hisoblanadi. Miyadagi neyronlar kabi bu tizim tugunlardan iborat bo\'lib, bir necha qatlamlarni tashkil qiladi: Kirish qatlami, yashirin qatlamlar va chiqish qatlami. Modul davomida "Deep Learning" (Chuqur o\'rganish) nima ekanligi va uning hozirgi kunda yuzni tanib olish (Facial Recognition) hamda ovozni ishlashdagi hissasini ko\'rib chiqamiz. Asosiy e\'tibor ko\'p qatlamli (multilayer perceptron) arxitekturalarga qaratiladi.', videoUrl: '' },
        { id: 'm4', title: 'AI etikasi va xavfsizlik', content: 'AI jadal rivojlanar ekan, uning axloqiy tomonlari dolzarbligicha qolmoqda. Sun\'iy intellektning jamiyat uchun keltiradigan ijobiy o\'zgarishlari qatorida, xavf va xatarlari ham yo\'q emas: Masalan, chuqur soxtalashtirish (Deepfakes), ma\'lumotlarning maxfiyligi buzilishi, va avtonom qurollar yaratilishi texnologiyalar etikasi darsining asosi hisoblanadi. Agar davlatlar va insoniyat to\'g\'ri qoidalarni (regulations) joriy qilmasa, AIning ommaviy ishsizlikka tortish ehtimollari mavjud. O\'quvchi bu modulda shaxsiy ma\'lumotlarni himoyalash va AI qarorlariga "xolislik" berish choralarini o\'rganadi.', videoUrl: '' },
        { id: 'm5', title: 'Yakuniy Imtihon', content: 'Barcha 4 ta modul doirasida o\'tilgan bilimlarni sinash uchun 15 ta yakuniy imtihon testi topshiriladi. Bu test AIdan nima maqsadda qanday foydalanish, shuningdek, sohaning nazariy asoslarini yaxshi bilishingizni tasdiqlab beradi. Muvaffaqiyat tilaymiz!', videoUrl: '' }
    ]
  },
  {
    title: 'Python dasturlash',
    description: 'Python dasturlash tilini noldan o\'rganing va amaliy dasturlarni yaratish.',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=500&q=80',
    modules: [
        { id: 'm1', title: 'Python asoslari va o\'rnatish', content: 'Python soddaligi hamda inson tiliga juda o\'xshashligi tufayli eng tez o\'sayotgan va talab yuqori bo\'lgan dasturlash tilidir. Ushbu modulda Python tilining imkoniyatlari, nima uchun Data tahlili yoki AI dasturlash aynan shu tilda yozilishi haqida bilib olasiz. Shuningdek, IDE (Integrated Development Environment - masalan PyCharm yoki VS Code) nima ekanligini, Python.org saytidan lokal kompyuterizga qanday o\'rnatishni hamda "Hello World!" deb chiqqan ilk dasturingizni yozishni o\'rganasiz. Syntaksisdagi indentatsiya (bo\'sh joy tashlash qoidalari) muhimligi tushuntiriladi.', videoUrl: '' },
        { id: 'm2', title: 'O\'zgaruvchilar va ma\'lumot tiplari', content: 'Dasturlashda o\'zgaruvchilarni "qutichalar" deb tasavvur qilsangiz bo\'ladi, bu qutichalarda ma\'lumotlarni saqlaymiz. Python tilidagi asosiy ma\'lumot tiplari quyidagilardir: Integer (butun sonlar: 5, -10), Float (haqiqiy sonlar: 3.14), String (matn: "Assalomu alaykum") va Boolean (Mantiqiy ifoda: True yoki False). O\'zgaruvchilardan tashqari biz katta hajmdagi ma\'lumotlarni strukturalangan holda ushlash uchun List (Ro\'yxatlar - []), Tuple (O\'zgarmas qatorlar - ()), va Dictionary (Lug\'atlar - {kalit:qiymat}) kabi kompleks ma\'lumot tuzilmalari bilan ishlashni batafsil o\'zlashtiramiz. Ularning ustida qilinadigan asosiy tayyor metodlar bilan tanishamiz.', videoUrl: '' },
        { id: 'm3', title: 'Shart operatorlari va tsikllar', content: 'Dasturimiz sun\'iy ong kabi qaror qabul qilishi uchun unga shartlar (Conditions) berish kerak. Python\'da bu "if, elif, va else" orqali amalga oshiriladi. Masalan, "Agar foydalanuvchining yoshi 18 dan katta bo\'lsa, tizimga ruxsat et, aks holda man qil." Bundan tashqari takrorlanadigan amallarni kun bo\'yi qo\'lda yozmaslik uchun Looplar (Tsikllar) kiritilgan. Modulda "for" va "while" hamda tsikllarni sindirishga xizmat qiladigan "break" va "continue" operatorlarining farqlarini o\'rganasiz. Ayniqsa, Listdagi elemanlarni tsikl qilib aylanib chiqish malakalarida juda kuchli fundamentga ega bo\'lasiz.', videoUrl: '' },
        { id: 'm4', title: 'Funksiyalar va OOP', content: 'Kodingiz takroriylikdan holi (DRY - Don\'t Repeat Yourself) bo\'lishi va tartibli ko\'rinishi uchun ular Funksiyalarga ("def" kalit so\'zi yordamida) ajratiladi. Har bir funksiya qandaydir kichikroq vazifani bajarishga ixtisoslashadi va o\'z qabul qiluvchi argumentlari (args, kwargs) bilan ishlaydi. Keyingi muhim bosqich bu OOP - Obyektga Yo\'naltirilgan Dasturlash (Object Oriented Programming). Olamdagi har qanday narsani kompyuterda bitta class ko\'rinishida yozish mumkin; ob\'yektning holatini atributlar (properties), harakatini esa metodlar belgilaydi. Class, Meros olish (Inheritance), va Polimorfizm OOP asoslari sifatida o\'tiladi.', videoUrl: '' },
        { id: 'm5', title: 'Yakuniy Imtihon', content: 'Amaliy bilimlar imtihonga aylanadi: ushbu qismgacha o\'rganilgan o\'zgaruvchilar, looplar va classlarlardan tortib barcha mavzular 15 ta sifatli savol sifatida beriladi. Testdan muvaffaqiyatli o\'tish orqali haqiqiy kod yozuvchi darajasiga yaqinlashasiz.', videoUrl: '' }
    ]
  },
  {
    title: 'Ta\'limda AI qo\'llanilishi',
    description: 'O\'qituvchilar va talabalar uchun AI asboblarini dars jarayoniga tatbiq etish strategiyalari.',
    thumbnail: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=500&q=80',
    modules: [
        { id: 'm1', title: 'Ta\'limda AIning roli', content: 'Ta\'lim sohasi sobiq konervativ jarayonlardan chiqib borayotgan bir vaqtda AI yordamchi sifatidagi rol o\'ynamoqda. Zamonaviy yondashuv shundaki, o\'qituvchi AI tufayli ishsiz qolmaydi, balki o\'z faoliyatini avtomatlashtirib oladi. AIning ta\'limdagi eng muhim afzalliklari sifatida biz jarayonlarning tezlashishi, barcha turdagi murakkab faktlarning interaktiv qayta ishlanishini (gamification) bilamiz. Sun\'iy intellektdan qochmaslik, balki uning potensialidan samarali foydalanish davr talabi, deb tushuntiriladi bu darsda.', videoUrl: '' },
        { id: 'm2', title: 'Darslik va kontent generatsiyasi', content: 'O\'qituvchilarni qiynaydigan eng katta muammo bu — qog\'ozbozlik, syllabus (rejalar) tayyorlash va o\'quv matnlari yaratishga ketadigan xarajat (vaqt va hajm). Modulimizning bundagi yechimi Generative AI asboblarini qo\'llashni darsdan o\'tishdir. ChatGPT yoki Gamma app kabi vositalarni yoritib beramiz — qanday qilib birgina so\'rov orqali 10 daqiqada slayd (Prezentatsiya) chiqarish mumkinligi va qanday qilib qiyin fanlarga doir tushunchalarni (masalan fizika va ximiya matnlarini) soddalashtirib qayta yozish yo\'llarini o\'rganasiz. Ovoz modullarini ta\'limga tiqish darslari ham mavjud.', videoUrl: '' },
        { id: 'm3', title: 'Talabalarni baholashda AI', content: 'Avtomatlashtirilgan baholash tizimlari bugungi kun mo\'jizasidir. Siz bir necha yuzlab o\'quvchilarga insho (essay) berganingizda, neyron tarmoqlar matnning morfologik tuzilishi va ma\'nosini o\'qish orqali grammatik, uslubiy xatolarni skaner qiladi va baho qo\'yib bera oladi. Qolaversa, "Plagiat (o\'g\'irlik)" bilan kurashish kabi vazifalarni AI asboblari yordamida tez fursatda bajarilishini o\'rganami. Bunday Turnitin kabi yechimlar orasida aslida AI modeli generatsiya qilinganini farqlovchi yana bir AI platformalar faoliyatini tanish.', videoUrl: '' },
        { id: 'm4', title: 'Moslashtirilgan ta\'lim (Personalized Learning)', content: 'Har bir o\'quvchi yoki talabaning individual miya tuzilishi va o\'zlashtirish tezligi bor. Hammaga bir xil poydevor berish o\'zini oqlamaydi. AIning Personalized Learning (Moslashtirilgan ta\'lim) texnologiyasi o\'quvchini qamrab olib, qayerda unga qo\'shimcha misol kerakligi yoki qachon mavzuni tezroq yopish kerakligini hisoblab chiqadi. ITS (Intelligent Tutoring Systems - Aqlli Repetitor tizimlari) platformalarining ishlash prinsiplari ushbu modulda aniq statistikalar bilan yoritiladi.', videoUrl: '' },
        { id: 'm5', title: 'Yakuniy Imtihon', content: 'AIning pedagogikada to\'g\'ri moslashtirilishi borasida yakuniy 15 ta testlar nazariya ustiga quriladi. Baholarni skanerlash yoki hujjat izlash uslubiyotlaringiz imtihonning asosi bo\'lad.', videoUrl: '' }
    ]
  },
  {
    title: 'Kiberpedagogika asoslari',
    description: 'Raqamli muhitda tarbiya, o\'qitish va o\'quvchining psixologik xavfsizligini ta\'minlash.',
    thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500&q=80',
    modules: [
        { id: 'm1', title: 'Kiberpedagogika tushunchasi', content: 'Kiberpedagogika an\'anaviy ta\'lim jarayonlarining to\'g\'ridan-to\'g\'ri zamonaviy texnologik va onlayn makonga ko\'chishidagi "tarbiya va ta\'limot" oqimidir. Bolaning nafaqat sinfdagi, balki virtual makondagi yashash tarzi uning shaxs shakllanishiga ta\'sir etadi. Keng miqyosda bu fanning maqsadi – internet kengliklaridagi ta\'lim jarayonida o\'quvchilarning faolligini, diqqatini boshqarishdir. Ushbu modul fanning kelib chiqish tarixi va "Homo Interneticus" raqamli odamini qayta anglashimiz haqida ma\'lumotlar beradi.', videoUrl: '' },
        { id: 'm2', title: 'Raqamli muhitda muloqot', content: 'Virtuallikda odamning cheklovlari buzilishi oson bo\'lib qoladi, kishilar kamerasi orqasida haqiqatda bo\'lmagan "virtual obraz" larni ham uydiradilar. O\'qituvchi va o\'quvchi o\'rtasidagi onlayn etika eng jiddiy komponentdir — chatdagi muomala, ovoz ohangi (Ton in text) va maktub yozuv shablonlari haqida bilamiz. Qanday qilib onlaynda empatik bo\'lish va o\'quvchini kompyuterining u tarafidan tushuna bilish strategiyalari taqdim etiladi.', videoUrl: '' },
        { id: 'm3', title: 'Kiberbulling va uni oldini olish', content: 'Kiberbulling – ijtimoiy tarmoqlar, messenjerlar bo\'ylab o\'smir yoki avlodni kamsitish, unga qarshi ma\'lumot tarqatish harakatlaridir. Uning an\'anaviy zorovonlikdan farqi – onlayn bo\'lgani tufayli tarqatilish masofasi chegarasiz va ma\'lumotni o\'chirish deyarli imkonsiz. Biz psixologik yondashuv qilib, qurbonlarni mudofaa qilish va ularga erta reabilitatsiyaviy choralar qo\'llash hamda, agresor o\'quvchini qanday barqarorlashtirish kerakligi bo\'ychia tahlillar o\'tkazamiz.', videoUrl: '' },
        { id: 'm4', title: 'Raqamli gigiyena', content: 'Axborot xuruji yuz bermoqda. Raqamli gigiyena esa inson ongiga singdirilayotgan toksik, keraksiz va yolg\'on feyk xabarlarni tartibga solish orqali virtual sog\'liqni asrashni ko\'zlaydi. Ushbu modul orqali biz shaxsiy ruxsatnomalar, turli onlayn fiishing xafvlaridan himoyalanish, ekran oldida turishning psixologik soatlarigacha yetib boramiz. Maqsad – o\'quvchida sog\'lom, to\'g\'ri mediamahsulotlarini saralash immunitetini yetishtirishdir.', videoUrl: '' },
        { id: 'm5', title: 'Yakuniy Imtihon', content: 'Yakuniy modulda psixologik xavfsizlik va onlayn etiketga tayangan 15 ta yakuniy imtihon beriladi. Tarbiyaviy savollar orqali kurs haqiqiy ma\'noda yakunlanadi.', videoUrl: '' }
    ]
  },
  {
    title: 'Ma\'lumotlar tahlili',
    description: 'Ma\'lumotlar yig\'ish, qayta ishlash va ular asosida to\'g\'ri qarorlar qabul qilish (Data Analytics).',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&q=80',
    modules: [
        { id: 'm1', title: 'Ma\'lumotlar tahlili nima?', content: 'Data Analytics – tartibsiz faktlar ketma-ketligini olib ularni qayta ishlovchi va jamiyatga/biznesga qimmatli insights (tushunchalar) taqdim etuvchi fandir. Siz uning Data Science bilan bo\'lgan farqlarini, shuningdek Big Data xususiyatlarini, jumladan katta hajmdagi xom ma\'lumotlarning qiymati xususida chuqur tushuncha olasiz. Modulning eng katta savoli bu — nima uchun "Ma\'lumot – XXI asrning nefti" deb nomlanganiga izoh topiladi.', videoUrl: '' },
        { id: 'm2', title: 'Excel va Google Sheets ilg\'or analitikasi', content: 'Oddiy elektron jadvallarning imkoniyatlarini noto\'g\'ri past baholaymiz. Excel bugungi kun eng ko\'p uchrovchi ma\'lumotlarni ajratish bo\'yicha mitti bazadir. Modulda siz Pivot jadval (Svodniy table) bilan katta o\'lchamdagi mijozlar, o\'quvchilarning bazasi ustida tahlil chizish, VLOOKUP, INDEX, MATCH kabi og\'ir funktsiyalarni va shartli tozalash (Data cleaning/filtering) usullarini professional ko\'z bilan batafsil yoritib o\'tamiz. Yomon sifatdagi ma\'lumotni ishlov berish sirlari mana shu yo\'lda uchrashadi.', videoUrl: '' },
        { id: 'm3', title: 'Ma\'lumotlarni vizualizatsiya qilish', content: 'Faqat sonlarga qarab xulosa qilish inson miyasi uchun zerikarli va qiyin. Tahlilni chiroyli va ochiq ko\'rinishga olib chiqish Visual (Grafika, Diagramma, Map) yechimlar orqali barpo qilinadi. Bu jarayonda biz Power BI, Tableau yoki sodda qilib aytganda Google Data Studio platformalarining o\'zgaruvchilarni diagrammalarga tortib borish imkoniyatlarini amaliy keyslarda izohlaymiz. Chiroyli bar chart va pie chart yasashda qoidalar qanday bo\'ladi – barchasini muhokama qilamiz.', videoUrl: '' },
        { id: 'm4', title: 'Ta\'limda ma\'lumotlar tahlili', content: 'Biznesda pul hisoblansa ta\'lim tizimida o\'zlashtirish metrikalari hisoblanadi. O\'quvchilardan yig\'ilgan natijalar, vaqt nazorati va qatnashish davomatlari – mana shu ma\'lumotlar ta\'lim analitikasining yosh sohasidir (Learning Analytics). Rahbariyat shu axborotlar asosida risklarni aniqlaydi (masalan ketib qolishi ehtimoli eng ko\'p o\'quvchini qutqaradi), oqilona o\'quv qarorlar yozadi va resurslarni bo\'lishtiradi. Asosiy maqsad raqamlar bilan gaplashuvchi zamonaviy metodistlarni ko\'rsatish.', videoUrl: '' },
        { id: 'm5', title: 'Yakuniy Imtihon', content: 'Modullardagi malaka bo\'yicha 15 ta yopiq (test) savollari sizga Excel analitikasidan va grafiklar chizish yechimlaridan keladi. Test tugallanishi analitikadagi savodxonligingiz isbotidir.', videoUrl: '' }
    ]
  },
  {
    title: 'Raqamli pedagogika',
    description: 'An\'anaviy ta\'limni zamonaviy raqamli innovatsiyalar bilan bog\'lash va o\'zlashtirish darslari.',
    thumbnail: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=500&q=80',
    modules: [
        { id: 'm1', title: 'Raqamli asrda ta\'lim', content: 'XXI asr ko\'nikmalariga moslashgan tizim eski dars metodikalarini (faqatgina kitob o\'quvini yod olish) orqada qoldirdi. Hozirda muloqot va ijodiylik bilan bir qatorda Raqamli Savodxonlik (Digital Literacy) juda muhim ko\'nikmaga aylandi. O\'quvchi faqatgina eshituvchi emas, raqamli asboblar orqali yaratuvchiga (Creator) aylanishi muhokama qilinadi. Modul yangi paradigmalarning avlodlarga (Gen Z va Alpha) mosligi tushuntiradi.', videoUrl: '' },
        { id: 'm2', title: 'Onlayn va Aralash (Blended) ta\'lim', content: 'Pedagoglar bugun ikki xil tushunchadan faol foydalanishi kerak. Sinxron darslar (Jonli zoom efir, sinfdagi muhit) va Asinxron darslar (oldindan tayyorlangan videolar, testlar va mustaqil ishlar orqali vaqtga qaram bo\'lmasdan). Aynan ushbu ikkisini birlashtirish orqali Blended (Aralash) ta\'lim kelib chiqqan. Flipped Classroom (To\'ntarilgan sinf) bo\'yicha bilim beriladi — bunda o\'quvchi uydan nazariyani AIda bajarib keladi va sinfda faqat ustoz ko\'magida analizlar quriladi.', videoUrl: '' },
        { id: 'm3', title: 'Interaktiv dars yaratish vositalari', content: 'Sinfxonani zerikarlikdan asrashning oson siri bor — uni o\'yini vaziyatlarga (Gamification) aylantirish. Endi taxtada bo\'r bilan xato izlanmaydi, balki onlayn platformalarda interaktiv ishlanadi. Kahoot orqali birgalikda poyga test ishlanadi, Padlet orqali "Elektron miya shturmi (Brainstorming)" lar qilinadi. Bularning barchasi darsdagi ijobiy motivatsiyalanishga tez olib boradigan texnologik va strategik instrumentlardir.', videoUrl: '' },
        { id: 'm4', title: 'Qayta aloqa (Feedback) madaniyati', content: 'Raqamli muhimta aloqa masalasi "tekshirildi: 4 baho" iborasi bilan tugallanmaydi. Biz obyektiv ravishda va izchillik bilan talabaning muammoli yarasiga tegmay turib xatolarni o\'ziga individual taqdim etish usullarini kuzatamiz. Audio-feedback (ovozli sharqlar) yozish vositalari yordamida o\'quvchi o\'qituvchini hissiyotlarini ham idrok etadi va emotsional rishta darslik samaradorligini barqarorlashtirib beradi.', videoUrl: '' },
        { id: 'm5', title: 'Yakuniy Imtihon', content: 'Raqamli vositalar, texnologik testlar yuzasidan barcha tajribani va konseptual g\'oyalarni so\'roqqa tutadigan 15 savol taqdim qilinadi. Uni bajarib sertifikatsiya zanjiridan o\'tasiz.', videoUrl: '' }
    ]
  },
  {
    title: 'ChatGPT va LLM',
    description: 'Katta til modellari (LLM) bilan samarali ishlash va so\'rov (Prompt) yozish san\'atini tadqiq etish.',
    thumbnail: 'https://images.unsplash.com/photo-1678996614407-1e5b1cb3cd68?w=500&q=80',
    modules: [
        { id: 'm1', title: 'LLM (Katta Til Modellari) nima?', content: 'LLM (Large Language Models) internetdagi butun ma\'lumotlar massivida tarbiyalangan, mantni tahlil qila oladigan va tuzilishi inson nutqiga o\'xshaydigan neyron tizimlardir. ChatGPT, Google Gemini, Claude kabilari nega bunday mo\'jizakor javob yozishinining siri ularni Autoregressiv bashorati (keyingi so\'zni taxmin qilib qo\'yishi) bilan tushuntiriladi. Transformer arxitekturalari, parametrlari va LLM larning galyutsinatsiya (noto\'g\'ri lof urishi, yoki yo\'q narsaga ishontirib berishi) xususiyatlari aniq yoritiladi.', videoUrl: '' },
        { id: 'm2', title: 'Prompt engineering asoslari', content: 'Sun\'iy intellekt xuddi kuchli jinga o\'xshaydi, to\'g\'ri buyruq (Prompt) bera olsangiz tilagingiz bajo. Lekin yomon Prompt shablonli gaplarni qaytaradi. Prompt Engineering aynan shuni hal etuvchi ilmdir. Aniq, qisqa kontekst berish formatini (Masalan: ACT AS / ROLE berish, Task belgilash, Formatni aniqlashtirish, va Cheklovlarni belgilash qonuni) yorqin misollarda sinaymiz. Shuningdek Zero-Shot va Few-Shot prompt yozuvlari haqida gap boradi.', videoUrl: '' },
        { id: 'm3', title: 'Murakkab vazifalarni AIda hal qilish', content: 'Sodda insholarni aytmasa ham yozadi, ammo murakkab ma\\lumot tahlilini qiyin matematika ishlarini to\'g\'ri taqsimotlash uchun biz "Chain of Thought (Zanjir fikrlash)" taktikasini o\'rganamiz: "Qadam ba qadam yechib ber" buyrug\'i tufayli ong qanday o\'zgarishi va xatoni qisqartirishi ko\'rsatiladi. Rol o\'ynash shablonlari yordamida esa dasturchi, huquqshunos yoki kopirayterdek o\'ylashi o\'tkaziladi.', videoUrl: '' },
        { id: 'm4', title: 'AI asistentlar yaratish va ish orni', content: 'Oddiy prompt yozishdan tashqari siz LLMlarga Custom Instructions (Shaxsiy dasturlar) berishingiz, ya\'ni ularning uzoq vaqt Sizning maqsadingizga yo\'nalgan Assistentga aylanib olishlarini mustahkam o\'rganamiz. Qanday qilib bir vaqtni o\'zida ijtimoiy tarmoq admini yoki kod xatolarini tekin tuzatuvchi agentlarni yasash va ish joyingizda ularni sizning vazifangizni 80% qisqartirishiga yo\'naltirish masalalari jamlangan.', videoUrl: '' },
        { id: 'm5', title: 'Yakuniy Imtihon', content: 'Haqiqiy "Prompt Engineer" bo\'la oldingizmi? So\'rov yo\'llashda formula va texnik usular bo\'yicha 15 ta kompleks holat testlarini tasdiqlaysiz.', videoUrl: '' }
    ]
  }
];

export async function seedCourses() {
  for (const c of defaultCourses) {
    await addDoc(collection(db, 'courses'), {
      ...c,
      createdAt: serverTimestamp()
    });
  }
}
